runtime: go
api_version: go1
application: [your application]
version: [your version]

handlers:
- url: /static
  static_dir: present/static
  application_readable: true

- url: /.*
  script: _go_app

nobuild_files: [glob for your presentation files]
